name: Picture Element
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99c7e6'
    - '#3e241a'
    - '#4875dc'
    - '#bf8453'
    - '#a4501f'
  brandStrength: 0.5
  lightness: 0.2904353393241763
  saturation: 0.9257819645572454
  rhythmicContrast: 0.8817562405019999
purpose: []
